server:
  port: 8088

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      master:
        url: jdbc:mysql://localhost:3306/master?serverTimezone=UTC
        username: root
        password: '03290329'
      slave:
        url: jdbc:mysql://localhost:3306/slave?serverTimezone=UTC
        username: root
        password: '03290329'