server:
  port: 13002

spring:
  application:
    name: kafka-consumer-demo
  kafka:
    bootstrap-servers: http://10.51.4.183:9092,http://10.51.4.183:9093,http://10.51.4.183:9094
    consumer:
      group-id: ideal-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer